server:
  port: 8080


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:mysql://localhost:3306/ecommercesystem?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: qwertYUIOP200512
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 16  #最大连接数
      minimum-idle: 2  #最小空闲连接数
      idle-timeout: 30000  #30s连接超时 未使用则断开
      max-lifetime: 600000  #连接最长时间 超过自动断开
      connection-timeout: 30000  #等待最长时间 超过报错

  # Redis 配置
  data:
    redis:
      host: localhost     # Redis 服务地址（默认127.0.0.1）
      port: 6379          # 默认端口
      password:           # 如果 Redis 没设密码可留空
      database: 0         # 默认数据库
      connect-timeout: 2s # 连接超时
      read-timeout: 2s    # 读取超时

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml   # 映射文件路径
  type-aliases-package: org.example.entity   # 包名xml直接用类名就行
  configuration:
    map-underscore-to-camel-case: true       # 数据库字段下划线自动转驼峰
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL 日志到控制台

# 日志
logging:
  level:
    org.example.mapper: debug
